---
# -*- coding: utf-8 -*-

stages:
  - lint-test
  - build
  - dockerize

go-lint-test:
  stage: lint-test
  image: golang:1.11
  before_script:
   - go get -u golang.org/x/lint/golint
  script:
    - golint -set_exit_status $(go list .)
    - go test .

go-build:
  stage: build
  image: golang:1.11
  before_script:
    - go get -u github.com/gin-gonic/gin
  script:
    - go build -v .

docker-build:
  stage: dockerize
  image: docker:stable
  before_script:
    - docker info
  script:
    - docker build -t simonkrenger/echoenv:latest .
